
---
title: "Data Publications"
description: "List of published data products"
title-block-style: none
keywords:
  - data science
  - lake
  - coastal wetland
  - methane
  - carbon
---

For annually-revised datasets, the citation for the most recent year is presented and the years of previous co-authored revisions are listed to the left.<br>
<i>\* indicates mentored undergraduate student</i>

<table style="width:100%;">
<tr>
<td>
<p><em>2025</em></p>
</td>
<td>
<p><span class="asl">Lewis, A. S. L.</span>, J. S. Rabaey, K. Attermeyer, P. Aurich, S. Bansal, M. Bartosiewicz, B. L. Bertolet, I. Bussmann, S. B. Cadieux, E. Calamita, C. Capelli, C. C. Carey, C. Cillero, F. Clayer, S. L. D'Ambrosio, T. A. Davidson, B. R. Deemer, B. A. Denfeld, W. Eckert, C. Esposito, P. Ford, A. Gorsky, N. A. Griffiths, H. F. Grossart, D. P. Hamilton, M. A. Holgerson, B. J. Huser, T. Iwata, J. Jansen, S. Jones, S. Juutinen, P. Kortelainen, M. Koschorreck, T. Kragh, A. Laas, T. Larmola, S. Läubli, I. Laurion, M. F. Lehmann, L. Liu, P. J. Martikainen, A. Matoušů, S. A. McCord, J. J. Montes-Pérez, D. Nizzoli, C. Ordóñez, M. Peacock, R. M. Pilla, V. Preskienis, J. Pu, T. Riis, T. Saarela, A. B. Santoso, C. J. Schubert, A. Sepulveda-Jauregui, B. S. Sherman, J. S. Sø, K. J. Stenehjem, K. E. Strock, K. Tsuchiya, K. Wendt-Potthoff, G. A. Weyhenmeyer, P. Znachor, and J. Zopfi. 2025. Greenhouse gas depth-profile data in 522 lakes worldwide ver 3. Environmental Data Initiative. [https://doi.org/10.6073/pasta/b2299c0d9804a662d6038923119b00c4](https://doi.org/10.6073/pasta/b2299c0d9804a662d6038923119b00c4)</p>
<p>Holmquist, J., E. L. Koontz, A. Carr, <span class="asl">A. S. L. Lewis</span>, P. Megonigal, G. Noyce, S. Parker, A. E. Stearns, S. H. Wulfing, C. M. Young, and B. Roberts. 2025. NASA Blue Methane Field Monitoring for Louisiana and the Chesapeake Bay, 2019-2021. Figshare. [https://doi.org/10.25573/serc.28373957.v1](https://doi.org/10.25573/serc.28373957.v1)</p>
</td>
</tr>
<tr>
<td>
<p><em>2025 2024 2023 2022</em></p>
</td>
<td>
<p>Carey, C. C., A. Breef-Pilz, and <span class="asl">A. S. L. Lewis</span>. 2025. Time series of methane and carbon dioxide diffusive fluxes using an Ultraportable Greenhouse Gas Analyzer (UGGA) for Falling Creek Reservoir and Beaverdam Reservoir in southwestern Virginia, USA during 2018-2024 ver 4. Environmental Data Initiative. [https://doi.org/10.6073/pasta/cdd88943c7990f28daa9b8ab7a6b9679](https://doi.org/10.6073/pasta/cdd88943c7990f28daa9b8ab7a6b9679)</p>
</td>
</tr>
<tr>
<td>
<p><em>2025 2024 2023 2022 2021 2019</p>
</td>
<td>
<p>Carey C. C., A. Breef-Pilz, <span class="asl">A. S. L. Lewis</span>, and K. K. Hoffman. 2025. Time series of high-frequency profiles of depth, temperature, dissolved oxygen, conductivity, specific conductance, chlorophyll a, turbidity, pH, oxidation-reduction potential, photosynthetically active radiation, colored dissolved organic matter, phycocyanin, phycoerythrin, and descent rate for Beaverdam Reservoir, Carvins Cove Reservoir, Falling Creek Reservoir, Gatewood Reservoir, and Spring Hollow Reservoir in southwestern Virginia, USA 2013-2024. Environmental Data Initiative. [https://doi.org/10.6073/pasta/75d1c9a57a49030c468ab19db3643c36](https://doi.org/10.6073/pasta/75d1c9a57a49030c468ab19db3643c36)</p>
</td>
</tr>
<tr>
<td>
<p><em>2024 2023 2022 2021</em></p>
</td>
<td>
<p>Carey, C. C., F. E. Olsson, B. R. Niederlehner, A. Breef-Pilz, and <span class="asl">A. S. L. Lewis</span>. 2024. Time series of dissolved methane and carbon dioxide concentrations for Falling Creek Reservoir and Beaverdam Reservoir in southwestern Virginia, USA during 2015&ndash;2023 ver 8. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/5a45f25ba0440a5efd32177a9103fb5f](https://doi.org/10.6073/pasta/5a45f25ba0440a5efd32177a9103fb5f)</p>
</td>
</tr>
<tr>
<td>
<p><em>2024</em></p>
</td>
<td>
<p>Carey, C. C., A. Breef-Pilz, A. D. Delany, A. G. Hounshell, <span class="asl">A. S. L. Lewis</span>, H. L. Wander, G. Haynie, M. Kricheldorf, and E. Tipper. 2024. Time series of high-frequency sensor data measuring water temperature, dissolved oxygen, conductivity, specific conductance, total dissolved solids, chlorophyll a, phycocyanin, fluorescent dissolved organic matter, turbidity at discrete depths, and water level in Beaverdam Reservoir, Virginia, USA in 2009-2023 ver 4. Environmental Data Initiative. [https://doi.org/10.6073/pasta/31bb6047e0ac367c60a61884338799c4](https://doi.org/10.6073/pasta/31bb6047e0ac367c60a61884338799c4)</p>
<p>McAfee, B. J., M. E. Lofton, A. Breef-Pilz, K. J. Goodman, R. T. Hensley, K. K. Hoffman, D. W. Howard, <span class="asl">A. S. L. Lewis</span>, D. M. McKnight, I. A. Oleksy, H. L. Wander, C. C. Carey, A. Karpatne, and P. C. Hanson. 2024.&nbsp;LakeBeD-US: Ecology Edition - a benchmark dataset of lake water quality time series and vertical profiles. Environmental Data Initiative. [https://doi.org/10.6073/pasta/c56a204a65483790f6277de4896d7140](https://doi.org/10.6073/pasta/c56a204a65483790f6277de4896d7140)</p>
</td>
</tr>
<tr>
<td>
<p><em>2023</em></p>
</td>
<td>
<p><span class="asl">Lewis, A. S. L.</span>, B. R. Niederlehner, A. Das*, H. L. Wander, M. E. Schreiber, and C. C. Carey. 2023. Experimental microcosm incubations assessing the effect of hypoxia on aqueous iron and organic carbon, pH, sediment organic carbon, and sediment iron-bound organic carbon ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/60a7784acef3038d3c8a16776a5b5746](https://doi.org/10.6073/pasta/60a7784acef3038d3c8a16776a5b5746)</p>
<p><span class="asl">Lewis, A. S. L.</span>, M. P. Lau, S. F. Jane, Y. Beeri-Shlevin, S. H. Burnet, F. Clayer, H. Feuchtmayr, H. Grossart, D. W. Howard, H. Mariash, J. Delgado-Martin, R. L. North, I. Oleksy, R. M. Pilla, K. C. Rose, A. P. Smagula, R. Sommaruga, S. E. Steiner, P. Verburg, D. Wain, G. A. Weyhenmeyer, and C. C. Carey. 2023. Dissolved oxygen, temperature, chlorophyll-a, total phosphorus, total nitrogen, and dissolved organic carbon at multiple depths in 822 lakes from 1921-2022 ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/2cd6628a942de2a8b12d2b19962712a0](https://doi.org/10.6073/pasta/2cd6628a942de2a8b12d2b19962712a0)</p>
<p>Schreiber, M. E., C. E. Wood, <span class="asl">A. S. L. Lewis</span>, N. W. Hammond, K. M. Krueger, M. E. Lofton, R. P. McClure, Z. W. Munger, A. Breef-Pilz, N. K. Ward, A. B. Gerling, B. R. Niederlehner, A. G. Hounshell, M. F. Verne, and C. C. Carey. 2023. Sediment trap time series data for Beaverdam Reservoir and Falling Creek Reservoir in southwestern Virginia, USA 2018 through 2022 ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/3e5d11ce1a38542d95250cdce18d6987](https://doi.org/10.6073/pasta/3e5d11ce1a38542d95250cdce18d6987)</p>
<p><span class="asl">Lewis, A. S. L.</span>, M. E. Schreiber, B. R. Niederlehner, A. Das*, and C. C. Carey. 2023. Total organic carbon, total nitrogen, and iron-bound organic carbon in surficial sediment and settling particulate material from Falling Creek and Beaverdam Reservoirs in 2019 and 2021 ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/a1d49c266b57465daa863cde4b1d4b4e](https://doi.org/10.6073/pasta/a1d49c266b57465daa863cde4b1d4b4e)</p>
</td>
</tr>
<tr>
<td>
<p><em>2022 2021</em></p>
</td>
<td>
<p>Carey, C. C., H. L. Wander, R. P. McClure, M. E. Lofton, K. D. Hamre, J. P. Doubek, A. B. Gerling, <span class="asl">A. S. L. Lewis</span>, and A. Breef-Pilz. 2022. Secchi depth data and discrete depth profiles of photosynthetically active radiation, temperature, dissolved oxygen, and pH for Beaverdam Reservoir, Carvins Cove Reservoir, Falling Creek Reservoir, Gatewood Reservoir, and Spring Hollow Reservoir in southwestern Virginia, USA 2013&ndash;2021 ver 10. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/887d8ab8c57fb8fdf3582507f3223cd6](https://doi.org/10.6073/pasta/887d8ab8c57fb8fdf3582507f3223cd6)</p>
</td>
</tr>
<tr>
<td>
<p><em>2022</em></p>
</td>
<td>
<p>Carey, C. C., <span class="asl">A. S. L.</span> <span class="asl">Lewis</span>, D. W. Howard, W. M. Woelmer, P. A. Gantzer, K. A. Bierlein, J. C. Little, and WVWA. 2022. Bathymetry and watershed area for Falling Creek Reservoir, Beaverdam Reservoir, and Carvins Cove Reservoir ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/352735344150f7e77d2bc18b69a22412](https://doi.org/10.6073/pasta/352735344150f7e77d2bc18b69a22412)</p>
<p>Jane, S. F., J. L. Mincer, M. P. Lau, <span class="asl">A. S. L. Lewis</span>, J. T. Stetler, K. C. Rose. 2022. Temperature and dissolved oxygen profiles for three Swiss lakes: 1972&ndash;2016 ver 6. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/7c08d0a4417f73d733d2a7eba43f57ea](https://doi.org/10.6073/pasta/7c08d0a4417f73d733d2a7eba43f57ea)</p>
</td>
</tr>
<tr>
<td>
<p><em>2021 2020</em></p>
</td>
<td>
<p>Carey, C. C., W. M. Woelmer, <span class="asl">A. S. L. Lewis</span>, A. Breef-Pilz, D. W. Howard, and B. J. Bookout. 2021. Time series of high-frequency sensor data measuring water temperature, dissolved oxygen, pressure, conductivity, specific conductance, total dissolved solids, chlorophyll a, phycocyanin, and fluorescent dissolved organic matter at discrete depths in Falling Creek Reservoir, Virginia, USA in 2018-2020 ver 5. Environmental Data Initiative. [https://doi.org/10.6073/pasta/88896f4a7208c9b7bddcf498258edf78](https://doi.org/10.6073/pasta/88896f4a7208c9b7bddcf498258edf78)</p>
</td>
</tr>
<tr>
<td>
<p><em>2021</em></p>
</td>
<td style="height: 141px; ;">
<p><span class="asl">Lewis, A. S. L.</span>, W. M. Woelmer, H. L. Wander, D. W. Howard, J. W. Smith, R. P. McClure, M. E. Lofton, N. W. Hammond, R. S. Corrigan, R. Q. Thomas, and C. C. Carey. 2021. Systematic review of near-term ecological forecasting literature published between 1932 and 2020 ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/c4bea94f100f39a6b73c7b9a577df214](https://doi.org/10.6073/pasta/c4bea94f100f39a6b73c7b9a577df214)</p>
<p>Lofton, M. E., D. W. Howard, R. P. McClure, H. L. Wander, W. M. Woelmer, A. G. Hounshell, <span class="asl">A. S. L. Lewis</span>, and C. C. Carey. 2021. Time series of phytoplankton biovolume at the depth of the vertical chlorophyll maximum in Falling Creek Reservoir, Vinton, VA, USA 2016&ndash;2019 ver 1. <em>Environmental Data Initiative</em>. [https://doi.org/10.6073/pasta/2de760e8b72e474c31e42526f5360f9a](https://doi.org/10.6073/pasta/2de760e8b72e474c31e42526f5360f9a)</p>
</td>
</tr>
<tr>
<td>
<p><em>2020</em></p>
</td>
<td>
<p>Wander, H. L., <span class="asl">A. S. L. Lewis,</span> H. L. Edwards, and D. C. Richardson. 2020. Zooplankton density and size data in Lake Awosting, Lake Minnewaska, and Mohonk Lake, NY, USA 2013&ndash;2018 ver 1. <em>Environmental Data Initiative.</em> [https://doi.org/10.6073/pasta/befde8268750ff108b59d8198eb989a1](https://doi.org/10.6073/pasta/befde8268750ff108b59d8198eb989a1)</p>
</td>
</tr>
</tbody>
</table>

<br><br>