
---
title: "Publications"
description: "Peer-reviewed publications from Abigail (Abby) Lewis"
title-block-style: none
keywords:
  - biogeochemistry
  - data science
  - ecological forecasting
  - lake
  - coastal wetland
  - methane
  - carbon
---

[ResearchGate](https://www.researchgate.net/profile/Abigail-Lewis-9) | [ORCID](http://orcid.org/0000-0001-9933-4542) | [Google Scholar](https://scholar.google.com/citations?user=RZ_wNlMAAAAJ)

<i>\* indicates mentored undergraduate student</i>

## In review
<ol reversed start = 32>
<li><span class="asl">Lewis, A. S. L.</span>, J. R. Holmquist, A. N. Al-Haj, Z. N. Read, R. L. Rich, J. P. Megonigal, and G. L. Noyce. Warming decreases the predictability of coastal wetland methane emissions. In review at <i>Ecosphere</i>.</li>
<br>
<li><span class="asl">Lewis, A. S. L.</span>, D. C. Richardson, D. W. Howard, C. C. Carey, Y. Amitai, S. Bansal, E. de Eyto, H-P Grossart, K. K. Hoffman, R. Hovel, L. Knoll, B. M. Kraemer, I. Oleksy, M. Schmid, R. Schwefel, D. Straile, X. Sun, G. A. Weyhenmeyer, W. M. Woelmer, S. Wollrab, P. Znachor. How should we analyze seasons and seasonality in lakes? In revision at <i>Limnology and Oceanography Letters</i>.</li>
<br>
<li>Hounshell, A. G., <span class="asl">A. S. L. Lewis</span>, D. W Howard, H. L. Wander, M. E. Lofton, P. C. Hanson, and C. C. Carey. Dissolved organic carbon dynamics are driven by water temperature, primary production, and anoxia over five years of whole-ecosystem experiments in a eutrophic reservoir. In review at <i>Aquatic Science.</i> \[[preprint](https://doi.org/10.22541/essoar.172926851.15664834/v2)\]</li>
<br>
<li>Colton, M., T. Fanara, S. Babin, <span class="asl">A. S. L. Lewis</span>, M. Dietze, C. Brown, M. Cotnoir, A. Caldas, K. Boyd. Ecological Forecasting for Readiness, Resilience, and Response. In revision at <i>Bulletin of the American Meteorological Society</i>.</li>
<br>
<li>Rabaey, J. S., <span class="asl">A. S. L. Lewis</span>, K. Attermeyer, P. Aurich, S. Bansal, M. Bartosiewicz, B. L. Bertolet, I. Bussmann, S. B. Cadieux, E. Calamita, C. Capelli, C. C. Carey, C. Cillero, F. Clayer, S. L. D'Ambrosio, T. A. Davidson, B. R. Deemer, B. A. Denfeld, W. Eckert, C. Esposito, P. Ford, A. Gorsky, N. A. Griffiths, H-P. Grossart, D. P. Hamilton, M. A. Holgerson, B. J. Huser, T. Iwata, J. Jansen, S. Jones, S. Juutinen, P. Kortelainen, M. Koschorreck, T. Kragh, A. Laas, T. Larmola, S. Läubli, I. Laurion, M. F. Lehmann, L. Liu, P. J. Martikainen, A. Matoušů, S. A. McCord, J. J. Montes-Pérez, D. Nizzoli, C. Ordóñez, M. Peacock, R. M. Pilla, V. Preskienis, J. Pu, T. Riis, T. Saarela, A. B. Santoso, C. J. Schubert, A. Sepulveda-Jauregui, B. S. Sherman, J. S. Sø, K. J. Stenehjem, K. J. Stenehjem, K. E. D. Strock, K. Tsuchiya, K. Wendt-Potthoff, G. A. Weyhenmeyer, P. Znachor, and J. Zopfi. Carbon dioxide and methane depth-profile concentrations in 544 lakes, ponds, and reservoirs worldwide. In review at <i>Scientific Data</i>.</li>
<br>
<li>Holmquist, J. R., A. R. Carr, and <span class="asl">A. S. L. Lewis</span>. Continuous Salinity Mapping for Coastal Wetlands in the United States. In revision at <i>Remote Sensing of the Environment</i>.</li>
<br>
<li>Sjodin, A., G. Stokes, C. Gallagher, M. Javadian, <span class="asl">A. S. L. Lewis</span>, C. Schreiner, L. Super, B. Tuschhoff, A. Willson, M. C. Dietze, J.  MacLachlan, J. Peters. Toward a standard lexicon for ecological forecasting. In revision at <i>Frontiers in Ecology and the Environment</i>.</li></ol>

## 2025

<ol reversed start = 25>
<li><span class="asl">Lewis, A. S. L.</span>, D. Mercado-Bettin, and C. C. Carey. 2025. Ecological memory contributes to a spatial mismatch in water quality trends between the surface and bottom waters of 382 temperate lakes. <i>Ecology Letters</i> 28(11): e70243. [https://doi.org/10.1111/ele.70243](https://doi.org/10.1111/ele.70243)</li>
<br>
<li>Olsson, F. E., C. C. Carey, G. Harrison, R. Ladwig, M. F. Lapeyrolerie, <span class="asl">A. S. L. Lewis</span>, M. E. Lofton, F. Montealegre-Mora, J. S. Rabaey, C. J. Robbins, X. Yang, R. Q. Thomas. 2025. What can we learn from 100,000 freshwater forecasts? A synthesis from the NEON Ecological Forecasting Challenge. <i>Ecological Applications</i>, 35(1): e70004. [https://doi.org/10.1002/eap.70004](https://doi.org/10.1002/eap.70004)</li>
<br>
<li>Wood, C. E., M. E. Schreiber, C. E. Bauer, A. Breef-Pilz, <span class="asl">A. S. L. Lewis</span>, N. W. Hammond, R. P. McClure, M. F. Verne, C. C. Carey. 2025. Preemptive activation of hypolimnetic oxygenation improves control of Fe and Mn in drinking water reservoirs. <i>Water Research</i>, 124722. [https://doi.org/10.1016/j.watres.2025.124722](https://doi.org/10.1016/j.watres.2025.124722)</li></ol>

## 2024

<ol reversed start = 22>
<li><span class="asl">Lewis, A. S. L.</span>, M. P. Lau, S. F. Jane, K. C. Rose, Y. Be'eri-Shlevin, S. H. Burnet, F. Clayer, H. Feuchtmayr, H. P. Grossart, D. W. Howard, H. Mariash, J. Delgado Martin, R. L. North, I. Oleksy, R. M. Pilla, A. P. Smagula, R. Sommaruga, S. E. Steiner, P. Verburg, D. Wain, G. A. Weyhenmeyer, C. C. Carey. 2024. Anoxia Begets Anoxia: a positive feedback to the deoxygenation of temperate lakes. <i>Global Change Biology</i>, 30(1), e17046. [http://doi.org/10.1111/gcb.17046](http://doi.org/10.1111/gcb.17046)<br>
<ul>
  <li>Reported in 36 news stories from 34 outlets ([Altmetric](https://wiley.altmetric.com/details/157228763/news))</li></ul></li>
<br>
<li><span class="asl">Lewis, A. S. L.</span>, A. Breef-Pilz, D. W. Howard, M. E. Lofton, F. Olsson, H. L. Wander, C. E. Wood, M. E. Schreiber, C. C. Carey. 2024. Reservoir Drawdown Highlights the Emergent Effects of Water Level Change on Reservoir Physics, Chemistry, and Biology. <i>JGR Biogeosciences</i>, 129, e2023JG007780. [https://doi.org/10.1029/2023JG007780](https://doi.org/10.1029/2023JG007780)</li>
<br>
<li>Mesman, J. P., C. C. Barbosa, <span class="asl">A. S. L. Lewis</span>, F. E. Olsson, S. Calhoun-Grosch, H.-P. Grossart, R. Ladwig, R. S. La Fuente, K. Münzner, L. G. T. Nkwalale, R. M. Pilla, K. Suresh and D. J. Wain. 2024. Challenges of Open Data in aquatic sciences: issues faced by data users and data providers. <i>Frontiers in Environmental Science</i>, 12:1497105. [https://doi.org/10.3389/fenvs.2024.1497105](https://doi.org/10.3389/fenvs.2024.1497105)</li>
<br>
<li>Howard, D. W., J. A. Brentrup, D. C. Richardson, <span class="asl">A. S. L. Lewis</span>, F. E. Olsson, and C. C. Carey. Variability in ice cover does not affect annual metabolism estimates in a small eutrophic reservoir. <i>JGR Biogeosciences</i>, 129, e2024JG008057. [https://doi.org/10.1029/2024JG008057](https://doi.org/10.1029/2024JG008057)</li>
<br>
<li>Malmborg, C. A., A. M. Willson, L. M. Bradley, M. A. Beatty, D. H. Klinges, G. Koren, <span class="asl">A. S. L. Lewis</span>, K. Oshinubi, and W. M. Woelmer. Defining Model Complexity: An Ecological Perspective. <i>Meteorological Applications</i>, 31(3), e2202. [https://doi.org/10.1002/met.2202](https://doi.org/10.1002/met.2202)</li>
<br>
<li>Wander, H. L., <span class="asl">A. S. L. Lewis</span>, D. W. Howard, M. E. Lofton, W. M. Woelmer, B. L. Brown, and C. C. Carey. 2024. Zooplankton community structure and diel migration patterns vary over hours, days, and years in the pelagic and littoral zone of a eutrophic reservoir. <i>Journal of Plankton Research</i>, fbae017. [https://doi.org/10.1093/plankt/fbae017](https://doi.org/10.1093/plankt/fbae017)</li>
<br>
<li>Man, X., C. Lei, K. A. Bierlein, L. D. Bryant. <span class="asl">A. S. L. Lewis</span>, C. C. Carey, J. C. Little. 2024. Computationally characterizing the diffusive boundary layer in lakes and reservoirs. <i>Journal of Soils and Sediments</i>, 24, 2132–2143. [https://doi.org/10.1007/s11368-024-03767-0](https://doi.org/10.1007/s11368-024-03767-0)</li>

## 2023

<ol reversed start = 15>
<li><span class="asl">Lewis, A. S. L.</span>, C. R. Rollinson, A. J. Allyn, J. Ashander, S. Brodie, C. B. Brookson, E. Collins, M. C. Dietze, A. S. Gallinat, N. Juvigny-Khenafou, G. Koren, D. J. McGlinn, J. A. Peters, N. R. Record, C. J. Robbins, J. Tonkin, and G. M. Wardle. 2023. The power of forecasts to advance ecological theory. <i>Methods in Ecology and Evolution</i>, 14(3), 746–756. [https://doi.org/10.1111/2041-210X.13955](https://doi.org/10.1111/2041-210X.13955)</li>
<br>
<li><span class="asl">Lewis, A. S. L.</span>, M. E. Schreiber, B. R. Niederlehner, A. Das*, N. W. Hammond, M. E. Lofton, H. L. Wander, C. C. Carey. 2023. Effects of Hypoxia on Coupled Iron and Carbon Cycling Differ by Timescale in Two Freshwater Reservoirs. <i>Journal of Geophysical Research: Biogeosciences</i>, 128(1), e2022JG007071. [https://doi.org/10.1029/2022JG007071](https://doi.org/10.1029/2022JG007071)</li>
<br>
<li><span class="asl">Lewis, A. S. L.</span>, D. W. Howard, G. Koren, C. Kowalski, J. McLachlan, J. A. Peters, O. Tabares, G. Smies. 2023. Ethics in ecological forecasting: a case-based learning set. <i>Teaching Issues and Experiments in Ecology</i>, 19(13). [https://doi.org/10.25334/5D99-Y019](https://doi.org/10.25334/5D99-Y019)</li>
<br>
<li><span class="asl">Lewis, A. S. L.</span>, G. O’Malley, G. K. Palissery, A. Hensley, C. López Lloreda, C. Perez, E. K. Bueren. 2023. Flipped Science Fair invites children to judge graduate student posters through a university-community partnership. <i>Journal of STEM Outreach</i>, 6(1), 1–12. [https://doi.org/10.15695/jstem/v6i1.14](https://doi.org/10.15695/jstem/v6i1.14)</li>
<br>
<li>Thomas, R.Q., C. Boettiger, C.C. Carey, M.C. Dietze, L.R. Johnson, M.A. Kenney, J.S. Mclachlan, J.A. Peters, E.R. Sokol, J.F. Weltzin, A. Willson, W.M. Woelmer, and Challenge Contributors. 2023. The NEON Ecological Forecasting Challenge. <i>Frontiers in Ecology and the Environment</i>, 21(3), 112–113. [https://doi.org/10.1002/fee.2616](https://doi.org/10.1002/fee.2616)</li>
<br>
<li>Woelmer, W. M., A. G. Hounshell, M. E. Lofton, H. L. Wander, <span class="asl">A. S. L. Lewis</span>, D. Scott, C. C. Carey. 2023. The importance of time and space in biogeochemical heterogeneity and processing along the reservoir ecosystem continuum. <i>Aquatic Sciences</i>, 85(2), 66. [https://doi.org/10.1007/s00027-023-00959-7](https://doi.org/10.1007/s00027-023-00959-7)</li></ol>

## 2022

<ol reversed start = 9><li><span class="asl">Lewis, A. S. L.</span>, W. M. Woelmer, H. L. Wander, D. W. Howard, J. W. Smith, R. P. McClure, M. E. Lofton, N. W. Hammond, R. S. Corrigan, R. Q. Thomas, C. C. Carey. 2022. Increased adoption of best practices in ecological forecasting enables comparisons of forecastability across systems. <i>Ecological Applications</i>, 32(2), e02500. [https://doi.org/10.1002/eap.2500](https://doi.org/10.1002/eap.2500)</li>
<br>
<li>Jane, S., J. L. Mincer, M. P. Lau, <span class="asl">A. S. L. Lewis</span>, J. T. Stetler, K. C. Rose. 2022. Longer duration of seasonal stratification contributes to widespread increases in lake hypoxia and anoxia. <i>Global Change Biology</i>, 29(4), 1009–1023. [https://doi.org/10.1111/gcb.16525](https://doi.org/10.1111/gcb.16525)</li>
<br>
<li>Lofton, M. E., D. W. Howard, R. P. McClure, H. L. Wander, W. M. Woelmer, A. G. Hounshell, <span class="asl">A. S. L. Lewis</span>, C. C. Carey. 2022. Experimental thermocline deepening alters vertical distribution and community structure of phytoplankton in a four-year whole-reservoir manipulation. <i>Freshwater Biology</i>, 67(11), 1903–1924. [https://doi.org/10.1111/fwb.13983](https://doi.org/10.1111/fwb.13983)</li>
<br>
<li>Carey C. C., P. C. Hanson, R. Q. Thomas, A. B. Gerling, A. Hounshell, <span class="asl">A. S. L. Lewis</span>, M. E. Lofton, R. P. McClure, H. L. Wander, W. M. Woelmer, B. R. Niederlehner, M. E. Schreiber. 2022. Anoxia decreases the magnitude of the carbon, nitrogen, and phosphorus sink in freshwaters. <i>Global Change Biology</i>, 28(16), 4861–4881. [https://doi.org/10.1111/gcb.16228](https://doi.org/10.1111/gcb.16228)</li></ol>

## 2021

<ol reversed start = 5>
<li>Carey, C. C., W. M. Woelmer, M. E. Lofton, R. J. Figueiredo, B. J. Bookout, R. S. Corrigan, V. Daneshmand, A. G. Hounshell, D. W. Howard, <span class="asl">A. S. L. Lewis</span>, R. P. McClure, H. L. Wander, N. K. Ward, R. Q. Thomas. 2021. Advancing lake and reservoir water quality management with near-term, iterative ecological forecasting. <i>Inland Waters</i>, 12(1), 107–120. [https://doi.org/10.1080/20442041.2020.1816421](https://doi.org/10.1080/20442041.2020.1816421)</li>
<br>
<li>Woelmer, W. M., L. M. Bradley, L. T. Haber, D. H. Klinges, <span class="asl">A. S. L. Lewis</span>, E. Mohr, C. L. Torrens, K. I. Wheeler, A. M. Willson. 2021. 10 Simple Rules for training yourself in an emerging field. <i>PLOS Computational Biology</i>, 17(10), e1009440. [https://doi.org/10.1371/journal.pcbi.1009440](https://doi.org/10.1371/journal.pcbi.1009440)</li></ol>

## 2020

<ol reversed start = 3>
<li><span class="asl">Lewis, A. S. L.</span>, B. S. Kim, H. L. Edwards, H. L. Wander, C. M. Garfield, H. E. Murphy, N. D. Poulin, S. D. Princiotta, K. C. Rose, A. E. Taylor, K. C. Weathers, C. R. Wigdahl-Perry, K. Yokota, D. C. Richardson, D. A. Bruesewitz. 2020. Prevalence of nitrogen and phosphorus colimitation of freshwater phytoplankton explained by nitrogen deposition and lake characteristics across northeastern United States. <i>Inland waters</i>, 10(1), 42–50. [https://doi.org/10.1080/20442041.2019.1664233](https://doi.org/10.1080/20442041.2019.1664233)</li></ol>

## 2018

<ol reversed start = 2>
<li>Frassl, M. A, D. P. Hamilton, B. A. Denfeld, E. de Eyto, S. E. Hampton, P. S. Keller, S. Sharma, <span class="asl">A. S. L. Lewis</span>, G. A. Weyhenmeyer, C. M. O'Reilly, M. E. Lofton, N. Catalán. 2018. Ten simple rules for collaboratively writing a multi-authored paper. <i>PLOS Computational Biology</i>, 14(11), e1006508. [https://doi.org/10.1371/journal.pcbi.1006508](https://doi.org/10.1371/journal.pcbi.1006508)</li></ol>

## 2017

<ol reversed>
<li>Lewis, S. E., J. J. Piatt., <span class="asl">A. S. L. Lewis</span>. 2017. Impact of a diet of native or non-native leaves on an amphipod Gammarus pseudolimnaeus. <i>Freshwater Science</i>, 36(4), 739–749. [https://doi.org/10.1086/694855](https://doi.org/10.1086/694855)</li></ol>
<br><br><br>
